public class LogEntries {
        
        public String CallerAcctNum {get; set;}
        public String ConnectorName {get; set;}
        public String ConnectorVersion {get; set;}
        public String DocCode {get; set;}
        public String FunctionName {get;set;}
        public String LogType {get; set;}
        public String LogLevel {get; set;}
        public String Message {get; set;}
        public String Operation {get; set;}
        public String ServiceURL {get; set;}
        public String Source {get; set;}
        public String tax {get; set;}
           
}